spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: 114514
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Swagger UI Description
apiTitle: "CaptionLive! API"
apiDescription: "A Project Management System for Fansub Group, developed by Aguri's GRavity Lab. Please see the GitHub page for more information at https://github.com/lijiaxi2018/CaptionLive"
apiVersion: "0.1"