name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_api_image:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
      - name: Build API Image
        working-directory: ./api
        run: |
          docker build --no-cache -t cl_api -f DockerFile .
  
  docker_hub_login:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
      - name: Login to Docker Hub
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
