name: Push Docker Images to DockerHub

on:
  push:
    branches: [ "main" ]

jobs:
  push_images:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build Images
        working-directory: ./api
        run: |
          docker build --no-cache -t cl_api -f DockerFile .
      
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push to DockerHub
        working-directory: ./api
        run: |
          docker tag cl_api lijiaxi2018/cl_api
          docker push lijiaxi2018/cl_api
      
