name: Docker Image CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build_api_image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build API Image
        working-directory: ./api
        run: |
          docker build --no-cache -t cl_api -f DockerFile .
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Push to Docker Hub
        working-directory: ./api
        run: |
          docker tag cl_api lijiaxi2018/test_cl_api
          docker push lijiaxi2018/test_cl_api
      
